
// use this tools
// https://www.willpeavy.com/minifier/
// http://tomeko.net/online_tools/cpp_text_escape.php?lang=en


const char HTML_page1[] PROGMEM  =  
"<!DOCTYPE html>\n"
"<html>\n"
"    <head>\n"
"          <style>\n"
"          .table{\n"
"            width: 100%;\n"
"            line-height: 32px;\n"
"          }\n"
"          .bars { \n"
"            float: left;\n"
"            height: 30px;\n"
"            width: 100px;\n"
"            line-height: 30px;\n"
"            border: 1px solid black;\n"
"            padding-left: 10px;\n"
"            padding-right: 10px;\n"
"            background: #FFFF99;\n"
"            text-align: center;\n"
"            }\n"
"          .bars0 { \n"
"            float: left;\n"
"            height: 30px;\n"
"            width: 150px;\n"
"            line-height: 30px;\n"
"            border: 1px solid black;\n"
"            padding-left: 10px;\n"
"            padding-right: 10px;\n"
"            background: #FFFF44;\n"
"            }\n"
"          .row{\n"
"            width: 100%;\n"
"            clear: both;            \n"
"            color: #000000;\n"
"            clear: both; \n"
"            font-weight: normal;\n"
"          }\n"
"           .rowhead{\n"
"            width: 100%;\n"
"            clear: both; \n"
"            background: #FFFF44;\n"
"            color: #ff0000;\n"
"            font-weight: bold;\n"
"          }\n"
"              \n"
"            .fon { background:blue; }\n"
"            .foff { background:red; }\n"
"            .fauto { background:gray; }\n"
"              \n"
"        </style>\n"
"\n"
"        <script>\t\t\n"
"\t\tfunction GetAllData()\n"
"        {\n"
"            var request = new XMLHttpRequest();\n"
"            request.onreadystatechange = function()\n"
"\t\t\t{\n"
"               if (this.readyState == 4 && this.status == 200) {\t\n"
"                   \n"
"                document.getElementById(\"state\").innerHTML = \"Connected\";\t\n"
"                   \n"
"                // get XML \n"
"                var xml = this.responseXML;\n"
"\n"
"                // get answers\n"
"                var answers= xml.getElementsByTagName(\"Programmi\")[0];\n"
"                for (var i = 0; i < answers.childNodes.length; i++) \n"
"                {   \n"
"                var name = answers.childNodes[i].nodeName;\n"
"                document.getElementById(\"state\").innerHTML = name;  \n"
"                var element = xml.getElementsByTagName(name)[0];\n"
"                var value = element.childNodes[0].nodeValue;\n"
"                document.getElementById(name).innerHTML = value;\n"
"                if ( value == 0)\n"
"                    document.getElementById(name).style.color = \"blue\";\n"
"                else\n"
"                    document.getElementById(name).style.color = \"red\";                    \n"
"                } \n"
"                   \n"
"                // get answers\n"
"                var answers= xml.getElementsByTagName(\"Stanze\")[0];\n"
"                for (var i = 0; i < answers.childNodes.length; i++) \n"
"                {   \n"
"                var name = answers.childNodes[i].nodeName;\n"
"                document.getElementById(\"state\").innerHTML = name;  \n"
"                var element = xml.getElementsByTagName(name)[0];\n"
"                var value = element.childNodes[0].nodeValue;\n"
"                document.getElementById(name).innerHTML = value;\n"
"                if ( value == 0)\n"
"                    document.getElementById(name).style.color = \"gray\";\n"
"                else \n"
"                    document.getElementById(name).style.color = \"blue\";                   \n"
"                }                   \n"
"            }\t\t\t\n"
"             }\n"
"            request.ontimeout = function()\n"
"\t\t\t{\t\t\n"
"\t\t\t\tdocument.getElementById(\"state\").innerHTML = \"NOT Connected\";\t\t\t\n"
"\t\t\t}\n"
"            \n"
"            request.open(\"GET\", \"ajax\", true);        \n"
"            request.send();\n"
"\t\t\tsetTimeout('GetAllData()', 5000);\n"
"        }\n"
"        </script>\n"
"    </head>\n"
"    <body onload=\"GetAllData()\">\n"
"\t <title>Ajax with eXML</title>\n"
"\t<! ************************************************************** !>\n"
"        <h1>-HOME-</h1>\n"
"        <span id=\"state\"> ..... </span>\n"
"        <h1>Programmi</h1>\n"
"        <div class=\"table\">\n"
"            <div class=\"rowhead\">\n"
"                <div class=\"bars0\">Programma </div>\n"
"                <div class=\"bars\">Stato</div></div>\n"
"            <div class=\"row\">\n"
"                <div class=\"bars0\">progBoilerACS </div>\n"
"                <div class=\"bars\" id=\"progBoilerACS\"> 0 </div>\n"
"                <div class=\"bars\"> <a href='/set?progBoilerACS=0'> <input type='button' id='btn' value='FORCE OFF' class='foff'/> </a></div>\n"
"                <div class=\"bars\"> <a href='/set?progBoilerACS=1'> <input type='button' id='btn' value='AUTO'      class='fauto'/></a></div>\n"
"                <div class=\"bars\"> <a href='/set?progBoilerACS=2'> <input type='button' id='btn' value='FORCE ON'  class='fon'/></a></div></div>\n"
"            <div class=\"row\">\n"
"                <div class=\"bars0\">progSummerAC </div>\n"
"                <div class=\"bars\" id=\"progSummerAC\">0</div></div>\n"
"            <div class=\"row\">\n"
"                <div class=\"bars0\">progWinterFIRE </div>\n"
"                <div class=\"bars\" id=\"progWinterFIRE\">0</div></div>\n"
"            <div class=\"row\">\n"
"                <div class=\"bars0\">progWinterPDC     </div>\n"
"                <div class=\"bars\" id=\"progWinterFIRE\">0</div></div>\n"
"            <div class=\"row\">\n"
"                <div class=\"bars0\">progWinterPDC_ECO </div>\n"
"                <div class=\"bars\" id=\"progWinterFIRE\">0</div></div>\n"
"            <div class=\"row\">\n"
"                <div class=\"bars0\">progAllRooms </div>\n"
"                <div class=\"bars\" id=\"progWinterFIRE\">0</div></div>\n"
"            <div class=\"row\">\n"
"                <div class=\"bars0\">progExternalLight </div>\n"
"                <div class=\"bars\" id=\"progWinterFIRE\">0</div></div>\n"
"\t    </div>\n"
"        <br>\n"
"        <h1>Stanze</h1>\n"
"\t\t<div class=\"table\">\n"
"             <div class=\"rowhead\">\n"
"                <div class=\"bars0\">Stanza </div>\n"
"                <div class=\"bars\">T</div></div>\n"
"            <div class=\"row\">\n"
"                <div class=\"bars0\">Cucina </div>\n"
"                <div class=\"bars\" id=\"tCucina\">0</div></div>\n"
"            <div class=\"row\">\n"
"                <div class=\"bars0\">Sala </div>\n"
"                <div class=\"bars\" id=\"tSala\">0</div></div>\n"
"            <div class=\"row\">\n"
"                <div class=\"bars0\">Bagno </div>\n"
"                 <div class=\"bars\" id=\"tBagno\">0</div></div>\n"
"\t   </div>\n"
"        </body>\n"
"</html>\n"
""
;
